name: release-solution
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/ALMLab
        solution-file: out/solutions/ALMLab.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to test env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://crmtest1.crm8.dynamics.com'
        user-name: 'ShifaMittal@acc0555.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: out/solutions/ALMLab.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://crmtest1.crm8.dynamics.com'
        user-name: 'ShifaMittal@acc0555.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: ALMTest
        managed: true
        solution-output-file: out/ship/ALMLab.zip

    - name: Upload the solution to GH artifact store
      uses: actions/upload-artifact@v4
      with:
        name: managedSolutions
        path: out/ship/ALMLab.zip

  release-to-prod:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://pracprod.crm8.dynamics.com/'
        user-name: 'ShifaMittal@acc0555.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: out/release/ALMLab.zip
        force-overwrite: true
        publish-changes: true
